#!/usr/bin/env bash

clang++ -std=c++11 -stdlib=libc++ -Weverything Benchmark.cpp LsmTree.cpp RunMetadata.cpp BloomFilter.cpp Entry.cpp MemoryRun.cpp Level.cpp FencePointer.cpp ResultSet.cpp -o Benchmark

